// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWkn8S_InHiF4Loy-SBkljvsMi9kUAbg',
    appId: '1:614499893538:web:4ae7017138e62a2fa3657b',
    messagingSenderId: '614499893538',
    projectId: 'celtas-b0bd5',
    authDomain: 'celtas-b0bd5.firebaseapp.com',
    storageBucket: 'celtas-b0bd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9r3l2FwThUIBp9XRM-Q-UxSxHfy7CbA',
    appId: '1:614499893538:android:a39fb1ffb1525e06a3657b',
    messagingSenderId: '614499893538',
    projectId: 'celtas-b0bd5',
    storageBucket: 'celtas-b0bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKBHRgU_Qg8KfI5sZD-BZBxrh6xmys7nY',
    appId: '1:614499893538:ios:dedb8298a55b584ca3657b',
    messagingSenderId: '614499893538',
    projectId: 'celtas-b0bd5',
    storageBucket: 'celtas-b0bd5.firebasestorage.app',
    androidClientId: '614499893538-afs3sgc7hkcc3f61b6mjdm0jf6g1vlbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.celtasMobile',
  );
}
